/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package vista;

/**
 *
 * @author J.A.R.R
 */
public class PanelRolUsuario extends javax.swing.JPanel {

    /**
     * Creates new form VistaRolUsuario
     */
    public PanelRolUsuario() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablarolusuario = new javax.swing.JTable();
        jPanel4 = new javax.swing.JPanel();
        btnSalirRol = new javax.swing.JButton();
        btnRegistroRol = new javax.swing.JButton();
        btnEditarRol = new javax.swing.JButton();
        btnBuscarRol = new javax.swing.JButton();
        btnEliminarRol = new javax.swing.JButton();
        btnNuevoRol = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        paneTipoRolUsuario = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        paneIdRolUsuario = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        paneDesRolUsuario = new javax.swing.JTextField();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tablarolusuario.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "ID Rol Usuario", "Tipo Rol Usuario", "Descripcion rol usuario"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tablarolusuario);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 10, -1, -1));

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 120, 600, 440));

        jPanel4.setBackground(new java.awt.Color(204, 0, 204));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnSalirRol.setBackground(new java.awt.Color(255, 51, 51));
        btnSalirRol.setFont(new java.awt.Font("Gill Sans Ultra Bold Condensed", 0, 18)); // NOI18N
        btnSalirRol.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/login.png"))); // NOI18N
        btnSalirRol.setText("Salir");
        jPanel4.add(btnSalirRol, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 70, 130, -1));

        btnRegistroRol.setFont(new java.awt.Font("Gill Sans Ultra Bold Condensed", 0, 18)); // NOI18N
        btnRegistroRol.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/registro.png"))); // NOI18N
        btnRegistroRol.setText("Registro");
        jPanel4.add(btnRegistroRol, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 30, -1, -1));

        btnEditarRol.setFont(new java.awt.Font("Gill Sans Ultra Bold Condensed", 0, 18)); // NOI18N
        btnEditarRol.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/editar.png"))); // NOI18N
        btnEditarRol.setText("Editar");
        jPanel4.add(btnEditarRol, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 30, -1, -1));

        btnBuscarRol.setFont(new java.awt.Font("Gill Sans Ultra Bold Condensed", 0, 18)); // NOI18N
        btnBuscarRol.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/buscar.png"))); // NOI18N
        btnBuscarRol.setText("Buscar");
        btnBuscarRol.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarRolActionPerformed(evt);
            }
        });
        jPanel4.add(btnBuscarRol, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 30, -1, -1));

        btnEliminarRol.setFont(new java.awt.Font("Gill Sans Ultra Bold Condensed", 0, 18)); // NOI18N
        btnEliminarRol.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/eliminar.png"))); // NOI18N
        btnEliminarRol.setText("Eliminar");
        btnEliminarRol.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarRolActionPerformed(evt);
            }
        });
        jPanel4.add(btnEliminarRol, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 30, -1, -1));

        btnNuevoRol.setFont(new java.awt.Font("Gill Sans Ultra Bold Condensed", 0, 18)); // NOI18N
        btnNuevoRol.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/nuevo.png"))); // NOI18N
        btnNuevoRol.setText("Nuevo");
        jPanel4.add(btnNuevoRol, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 20, 130, 40));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/enderman_25744.png"))); // NOI18N
        jPanel4.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 50, 70));

        jSeparator1.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator1.setForeground(new java.awt.Color(0, 0, 0));
        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel4.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 10, 10, 100));

        jSeparator2.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator2.setForeground(new java.awt.Color(0, 0, 0));
        jPanel4.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, -1));

        add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 120));

        jPanel2.setBackground(new java.awt.Color(51, 51, 51));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Gill Sans Ultra Bold Condensed", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 0, 255));
        jLabel2.setText("ID Rol Usuario");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, -1, -1));

        paneTipoRolUsuario.setFont(new java.awt.Font("Gill Sans Ultra Bold Condensed", 0, 14)); // NOI18N
        paneTipoRolUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                paneTipoRolUsuarioActionPerformed(evt);
            }
        });
        jPanel2.add(paneTipoRolUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, 160, -1));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/minecraft_logo_icon_168099 (2).png"))); // NOI18N
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 0, -1, -1));

        paneIdRolUsuario.setFont(new java.awt.Font("Gill Sans Ultra Bold Condensed", 0, 14)); // NOI18N
        paneIdRolUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                paneIdRolUsuarioActionPerformed(evt);
            }
        });
        jPanel2.add(paneIdRolUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 160, -1));

        jLabel4.setFont(new java.awt.Font("Gill Sans Ultra Bold Condensed", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 0, 255));
        jLabel4.setText("Tipo Rol Usuario");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, -1, -1));

        jLabel5.setFont(new java.awt.Font("Gill Sans Ultra Bold Condensed", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 0, 255));
        jLabel5.setText("Descripcion Rol Usuario");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 270, -1, -1));

        paneDesRolUsuario.setFont(new java.awt.Font("Gill Sans Ultra Bold Condensed", 0, 14)); // NOI18N
        paneDesRolUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                paneDesRolUsuarioActionPerformed(evt);
            }
        });
        jPanel2.add(paneDesRolUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 300, 160, -1));

        add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 120, 200, 440));
    }// </editor-fold>//GEN-END:initComponents

    private void btnBuscarRolActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarRolActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnBuscarRolActionPerformed

    private void btnEliminarRolActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarRolActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnEliminarRolActionPerformed

    private void paneTipoRolUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_paneTipoRolUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_paneTipoRolUsuarioActionPerformed

    private void paneIdRolUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_paneIdRolUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_paneIdRolUsuarioActionPerformed

    private void paneDesRolUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_paneDesRolUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_paneDesRolUsuarioActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnBuscarRol;
    public javax.swing.JButton btnEditarRol;
    public javax.swing.JButton btnEliminarRol;
    public javax.swing.JButton btnNuevoRol;
    public javax.swing.JButton btnRegistroRol;
    public javax.swing.JButton btnSalirRol;
    public javax.swing.JLabel jLabel2;
    public javax.swing.JLabel jLabel4;
    public javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    public javax.swing.JTextField paneDesRolUsuario;
    public javax.swing.JTextField paneIdRolUsuario;
    public javax.swing.JTextField paneTipoRolUsuario;
    public javax.swing.JTable tablarolusuario;
    // End of variables declaration//GEN-END:variables
}
