/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package vista;

/**
 *
 * @author aurit
 */
public class panelDashBoardPuntoVenta extends javax.swing.JPanel {

    /**
     * Creates new form VistaDashBoardPuntoVenta
     */
    public panelDashBoardPuntoVenta() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelMenu = new javax.swing.JPanel();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaproducto = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        txtSubtotal = new javax.swing.JTextField();
        txtTola = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtbuscraid = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        panelEnca = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        panelMenu1 = new javax.swing.JPanel();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel7 = new javax.swing.JLabel();
        btnAgregarproducto = new javax.swing.JButton();
        btnCancelarVenta = new javax.swing.JButton();
        BorrarProductobtn = new javax.swing.JButton();
        NuevaVentabtn = new javax.swing.JButton();
        Editarbtn = new javax.swing.JButton();
        btnSalirVenta = new javax.swing.JButton();
        ticketbtn = new javax.swing.JButton();
        txtIVA1 = new javax.swing.JTextField();
        BuscarIdbtn = new javax.swing.JButton();
        FinalizarVentaBTN = new javax.swing.JButton();

        panelMenu.setBackground(new java.awt.Color(102, 102, 255));
        panelMenu.setMinimumSize(new java.awt.Dimension(170, 160));
        panelMenu.setPreferredSize(new java.awt.Dimension(224, 640));
        panelMenu.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jSeparator2.setPreferredSize(new java.awt.Dimension(200, 10));
        panelMenu.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, -1, 10));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/logmai.png"))); // NOI18N
        panelMenu.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, -1, -1));

        tablaproducto.setBackground(new java.awt.Color(102, 102, 102));
        tablaproducto.setForeground(new java.awt.Color(102, 102, 102));
        tablaproducto.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tablaproducto);

        jLabel4.setText("Buscar producto por id:");

        txtSubtotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSubtotalActionPerformed(evt);
            }
        });

        txtTola.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTolaActionPerformed(evt);
            }
        });

        jLabel2.setText("I.V.A");

        txtbuscraid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtbuscraidActionPerformed(evt);
            }
        });

        jLabel3.setText("TOTAL");

        jLabel1.setText("Subtotal");

        panelEnca.setBackground(new java.awt.Color(0, 51, 102));
        panelEnca.setPreferredSize(new java.awt.Dimension(800, 80));
        panelEnca.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/maigra.png"))); // NOI18N
        panelEnca.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 10, 270, 50));

        panelMenu1.setBackground(new java.awt.Color(51, 51, 255));
        panelMenu1.setMinimumSize(new java.awt.Dimension(170, 160));
        panelMenu1.setPreferredSize(new java.awt.Dimension(224, 640));
        panelMenu1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jSeparator3.setPreferredSize(new java.awt.Dimension(200, 10));
        panelMenu1.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, -1, 10));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/logmai.png"))); // NOI18N
        panelMenu1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, -1, -1));

        btnAgregarproducto.setBackground(new java.awt.Color(102, 102, 255));
        btnAgregarproducto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/registro.png"))); // NOI18N
        btnAgregarproducto.setText("Agregar");
        btnAgregarproducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarproductoActionPerformed(evt);
            }
        });
        panelMenu1.add(btnAgregarproducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, 160, -1));

        btnCancelarVenta.setBackground(new java.awt.Color(102, 102, 255));
        btnCancelarVenta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/cancelar.png"))); // NOI18N
        btnCancelarVenta.setText("Cancelar");
        btnCancelarVenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarVentaActionPerformed(evt);
            }
        });
        panelMenu1.add(btnCancelarVenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 250, 160, -1));

        BorrarProductobtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/eliminar.png"))); // NOI18N
        BorrarProductobtn.setText("Borrar");
        BorrarProductobtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BorrarProductobtnActionPerformed(evt);
            }
        });
        panelMenu1.add(BorrarProductobtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 320, 160, -1));

        NuevaVentabtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/nuevo.png"))); // NOI18N
        NuevaVentabtn.setText("Nuevo");
        NuevaVentabtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NuevaVentabtnActionPerformed(evt);
            }
        });
        panelMenu1.add(NuevaVentabtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 480, 160, -1));

        Editarbtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/editar.png"))); // NOI18N
        Editarbtn.setText("Editar");
        Editarbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditarbtnActionPerformed(evt);
            }
        });
        panelMenu1.add(Editarbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 400, 160, -1));

        btnSalirVenta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/login.png"))); // NOI18N
        btnSalirVenta.setText("Salir");
        btnSalirVenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirVentaActionPerformed(evt);
            }
        });
        panelMenu1.add(btnSalirVenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 560, 160, -1));

        ticketbtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/factura.png"))); // NOI18N
        ticketbtn.setText("Generar Ticket");

        txtIVA1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIVA1ActionPerformed(evt);
            }
        });

        BuscarIdbtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/buscar.png"))); // NOI18N

        FinalizarVentaBTN.setText("Finalizar");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelMenu1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelEnca, javax.swing.GroupLayout.DEFAULT_SIZE, 822, Short.MAX_VALUE)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(36, 36, 36)
                                .addComponent(ticketbtn))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(59, 59, 59)
                                .addComponent(FinalizarVentaBTN)))
                        .addGap(143, 143, 143)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(193, 193, 193))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(38, 38, 38)
                                .addComponent(txtSubtotal, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(41, 41, 41)
                        .addComponent(txtTola, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(47, 91, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addComponent(jLabel4)
                        .addGap(18, 18, 18)
                        .addComponent(txtbuscraid, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(BuscarIdbtn)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel3)
                        .addGap(134, 134, 134))))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(673, Short.MAX_VALUE)
                    .addComponent(txtIVA1, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(259, 259, 259)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelEnca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(BuscarIdbtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtTola, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtSubtotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel3)
                        .addGap(74, 74, 74))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(txtbuscraid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(133, 133, 133)
                        .addComponent(ticketbtn)
                        .addGap(18, 18, 18)
                        .addComponent(FinalizarVentaBTN)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addComponent(panelMenu1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(472, Short.MAX_VALUE)
                    .addComponent(txtIVA1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(146, 146, 146)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalirVentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirVentaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSalirVentaActionPerformed

    private void NuevaVentabtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NuevaVentabtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NuevaVentabtnActionPerformed

    private void BorrarProductobtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BorrarProductobtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BorrarProductobtnActionPerformed

    private void EditarbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditarbtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EditarbtnActionPerformed

    private void btnAgregarproductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarproductoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAgregarproductoActionPerformed

    private void txtTolaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTolaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTolaActionPerformed

    private void txtbuscraidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtbuscraidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtbuscraidActionPerformed

    private void txtSubtotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSubtotalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSubtotalActionPerformed

    private void btnCancelarVentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarVentaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCancelarVentaActionPerformed

    private void txtIVA1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIVA1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIVA1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton BorrarProductobtn;
    public javax.swing.JButton BuscarIdbtn;
    public javax.swing.JButton Editarbtn;
    public javax.swing.JButton FinalizarVentaBTN;
    private javax.swing.JButton NuevaVentabtn;
    public javax.swing.JButton btnAgregarproducto;
    public javax.swing.JButton btnCancelarVenta;
    public javax.swing.JButton btnSalirVenta;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JPanel panelEnca;
    private javax.swing.JPanel panelMenu;
    private javax.swing.JPanel panelMenu1;
    public javax.swing.JTable tablaproducto;
    public javax.swing.JButton ticketbtn;
    public javax.swing.JTextField txtIVA1;
    public javax.swing.JTextField txtSubtotal;
    public javax.swing.JTextField txtTola;
    public javax.swing.JTextField txtbuscraid;
    // End of variables declaration//GEN-END:variables
}
