/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package vista;

/**
 *
 * @author 52558
 */
public class PanelProducto extends javax.swing.JPanel {

    /**
     * Creates new form PanelProducto
     */
    public PanelProducto() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnRegistro = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnRegistroProducto = new javax.swing.JButton();
        btnEditarProducto = new javax.swing.JButton();
        btnBuscarProducto = new javax.swing.JButton();
        btnEliminarProducto = new javax.swing.JButton();
        btnNuevoProducto = new javax.swing.JButton();
        btnSaliirProducto = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jPanel2 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        panelIdProducto = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        panelNombreProducto = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        panelPrecio = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        panelDescripcion = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        panelExistencia = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        PanelCodigo = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaProductos = new javax.swing.JTable();

        btnRegistro.setFont(new java.awt.Font("Gill Sans Ultra Bold Condensed", 0, 18)); // NOI18N
        btnRegistro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/registro.png"))); // NOI18N
        btnRegistro.setText("Registro");

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane2.setViewportView(jTextArea1);

        setMaximumSize(new java.awt.Dimension(800, 560));
        setPreferredSize(new java.awt.Dimension(800, 560));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 255, 255));
        jPanel1.setMinimumSize(new java.awt.Dimension(800, 110));
        jPanel1.setPreferredSize(new java.awt.Dimension(800, 110));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/allay.jpg"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 50, 70));

        btnRegistroProducto.setFont(new java.awt.Font("Gill Sans Ultra Bold Condensed", 0, 18)); // NOI18N
        btnRegistroProducto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/registro.png"))); // NOI18N
        btnRegistroProducto.setText("Registro");
        jPanel1.add(btnRegistroProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 40, -1, -1));

        btnEditarProducto.setFont(new java.awt.Font("Gill Sans Ultra Bold Condensed", 0, 18)); // NOI18N
        btnEditarProducto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/editar.png"))); // NOI18N
        btnEditarProducto.setText("Editar");
        jPanel1.add(btnEditarProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 40, -1, -1));

        btnBuscarProducto.setFont(new java.awt.Font("Gill Sans Ultra Bold Condensed", 0, 18)); // NOI18N
        btnBuscarProducto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/buscar.png"))); // NOI18N
        btnBuscarProducto.setText("Buscar");
        btnBuscarProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarProductoActionPerformed(evt);
            }
        });
        jPanel1.add(btnBuscarProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 40, -1, -1));

        btnEliminarProducto.setFont(new java.awt.Font("Gill Sans Ultra Bold Condensed", 0, 18)); // NOI18N
        btnEliminarProducto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/eliminar.png"))); // NOI18N
        btnEliminarProducto.setText("Eliminar");
        btnEliminarProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarProductoActionPerformed(evt);
            }
        });
        jPanel1.add(btnEliminarProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 40, -1, -1));

        btnNuevoProducto.setFont(new java.awt.Font("Gill Sans Ultra Bold Condensed", 0, 18)); // NOI18N
        btnNuevoProducto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/nuevo.png"))); // NOI18N
        btnNuevoProducto.setText("Nuevo");
        jPanel1.add(btnNuevoProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(648, 20, 130, 40));

        btnSaliirProducto.setBackground(new java.awt.Color(255, 51, 51));
        btnSaliirProducto.setFont(new java.awt.Font("Gill Sans Ultra Bold Condensed", 0, 18)); // NOI18N
        btnSaliirProducto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/login.png"))); // NOI18N
        btnSaliirProducto.setText("Salir");
        jPanel1.add(btnSaliirProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 70, 130, -1));

        jSeparator1.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator1.setForeground(new java.awt.Color(0, 0, 0));
        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 10, 10, 100));

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 120));

        jPanel2.setBackground(new java.awt.Color(51, 51, 51));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/minecraft_logo_icon_168099 (2).png"))); // NOI18N
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(36, 5, -1, -1));

        jLabel2.setFont(new java.awt.Font("Gill Sans Ultra Bold Condensed", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 255, 255));
        jLabel2.setText("ID Producto");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, -1, -1));

        panelIdProducto.setFont(new java.awt.Font("Gill Sans Ultra Bold Condensed", 0, 14)); // NOI18N
        panelIdProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                panelIdProductoActionPerformed(evt);
            }
        });
        jPanel2.add(panelIdProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 160, -1));

        jLabel4.setFont(new java.awt.Font("Gill Sans Ultra Bold Condensed", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 255, 255));
        jLabel4.setText("Codigo");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, -1, -1));

        panelNombreProducto.setFont(new java.awt.Font("Gill Sans Ultra Bold Condensed", 0, 14)); // NOI18N
        panelNombreProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                panelNombreProductoActionPerformed(evt);
            }
        });
        jPanel2.add(panelNombreProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, 160, -1));

        jLabel5.setFont(new java.awt.Font("Gill Sans Ultra Bold Condensed", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 255, 255));
        jLabel5.setText("Descripcion");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 370, -1, -1));

        panelPrecio.setFont(new java.awt.Font("Gill Sans Ultra Bold Condensed", 0, 14)); // NOI18N
        panelPrecio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                panelPrecioActionPerformed(evt);
            }
        });
        jPanel2.add(panelPrecio, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 330, 160, -1));

        jLabel7.setFont(new java.awt.Font("Gill Sans Ultra Bold Condensed", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 255, 255));
        jLabel7.setText("Precio");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 310, -1, -1));

        panelDescripcion.setFont(new java.awt.Font("Gill Sans Ultra Bold Condensed", 0, 14)); // NOI18N
        panelDescripcion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                panelDescripcionActionPerformed(evt);
            }
        });
        jPanel2.add(panelDescripcion, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 390, 160, -1));

        jLabel8.setFont(new java.awt.Font("Gill Sans Ultra Bold Condensed", 0, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 255, 255));
        jLabel8.setText("Existencia");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, -1, -1));

        panelExistencia.setFont(new java.awt.Font("Gill Sans Ultra Bold Condensed", 0, 14)); // NOI18N
        panelExistencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                panelExistenciaActionPerformed(evt);
            }
        });
        jPanel2.add(panelExistencia, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 270, 160, -1));

        jLabel6.setFont(new java.awt.Font("Gill Sans Ultra Bold Condensed", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 255, 255));
        jLabel6.setText("Nombre");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, -1, -1));

        PanelCodigo.setFont(new java.awt.Font("Gill Sans Ultra Bold Condensed", 0, 14)); // NOI18N
        PanelCodigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PanelCodigoActionPerformed(evt);
            }
        });
        jPanel2.add(PanelCodigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, 160, -1));

        add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 120, 200, 440));

        tablaProductos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Id", "Codigo", "Nombre", "Existencia", "Precio", "Descripcion"
            }
        ));
        jScrollPane1.setViewportView(tablaProductos);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 120, 600, 440));
    }// </editor-fold>//GEN-END:initComponents

    private void btnBuscarProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarProductoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnBuscarProductoActionPerformed

    private void btnEliminarProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarProductoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnEliminarProductoActionPerformed

    private void panelIdProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_panelIdProductoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_panelIdProductoActionPerformed

    private void panelNombreProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_panelNombreProductoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_panelNombreProductoActionPerformed

    private void panelPrecioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_panelPrecioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_panelPrecioActionPerformed

    private void panelDescripcionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_panelDescripcionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_panelDescripcionActionPerformed

    private void panelExistenciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_panelExistenciaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_panelExistenciaActionPerformed

    private void PanelCodigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PanelCodigoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PanelCodigoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JTextField PanelCodigo;
    public javax.swing.JButton btnBuscarProducto;
    public javax.swing.JButton btnEditarProducto;
    public javax.swing.JButton btnEliminarProducto;
    public javax.swing.JButton btnNuevoProducto;
    public javax.swing.JButton btnRegistro;
    public javax.swing.JButton btnRegistroProducto;
    public javax.swing.JButton btnSaliirProducto;
    private javax.swing.JLabel jLabel1;
    public javax.swing.JLabel jLabel2;
    public javax.swing.JLabel jLabel4;
    public javax.swing.JLabel jLabel5;
    public javax.swing.JLabel jLabel6;
    public javax.swing.JLabel jLabel7;
    public javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextArea jTextArea1;
    public javax.swing.JTextField panelDescripcion;
    public javax.swing.JTextField panelExistencia;
    public javax.swing.JTextField panelIdProducto;
    public javax.swing.JTextField panelNombreProducto;
    public javax.swing.JTextField panelPrecio;
    public javax.swing.JTable tablaProductos;
    // End of variables declaration//GEN-END:variables
}
