/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

/**
 *
 * @author J.A.R.R
 */
public class VistaDashBoardAdmin extends javax.swing.JFrame {

    /**
     * Creates new form VistaDashBoardAdmin
     */
    public VistaDashBoardAdmin() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelMenu = new javax.swing.JPanel();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        btnRolUsuarios = new javax.swing.JButton();
        btnUsuarios = new javax.swing.JButton();
        panelEnca = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        panelContenedor = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelMenu.setBackground(new java.awt.Color(0, 0, 0));
        panelMenu.setMinimumSize(new java.awt.Dimension(170, 160));
        panelMenu.setPreferredSize(new java.awt.Dimension(224, 640));
        panelMenu.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jSeparator2.setPreferredSize(new java.awt.Dimension(200, 10));
        panelMenu.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, -1, 10));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/logmai.png"))); // NOI18N
        panelMenu.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, -1, -1));

        btnRolUsuarios.setBackground(new java.awt.Color(204, 0, 204));
        btnRolUsuarios.setFont(new java.awt.Font("Eras Bold ITC", 0, 18)); // NOI18N
        btnRolUsuarios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/enderman_25744.png"))); // NOI18N
        btnRolUsuarios.setText("RolUsuario");
        btnRolUsuarios.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnRolUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRolUsuariosActionPerformed(evt);
            }
        });
        panelMenu.add(btnRolUsuarios, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 260, 200, 70));

        btnUsuarios.setBackground(new java.awt.Color(0, 204, 0));
        btnUsuarios.setFont(new java.awt.Font("Eras Bold ITC", 0, 18)); // NOI18N
        btnUsuarios.setForeground(new java.awt.Color(204, 204, 204));
        btnUsuarios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/minecraft_icon_132202.png"))); // NOI18N
        btnUsuarios.setText("    Usuarios");
        btnUsuarios.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUsuariosActionPerformed(evt);
            }
        });
        panelMenu.add(btnUsuarios, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, 200, 70));

        getContentPane().add(panelMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        panelEnca.setBackground(new java.awt.Color(0, 204, 0));
        panelEnca.setPreferredSize(new java.awt.Dimension(800, 80));
        panelEnca.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/maigra.png"))); // NOI18N
        panelEnca.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 20, 270, 50));

        getContentPane().add(panelEnca, new org.netbeans.lib.awtextra.AbsoluteConstraints(224, 0, 800, -1));

        panelContenedor.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout panelContenedorLayout = new javax.swing.GroupLayout(panelContenedor);
        panelContenedor.setLayout(panelContenedorLayout);
        panelContenedorLayout.setHorizontalGroup(
            panelContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 800, Short.MAX_VALUE)
        );
        panelContenedorLayout.setVerticalGroup(
            panelContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 560, Short.MAX_VALUE)
        );

        getContentPane().add(panelContenedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(224, 80, 800, 560));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRolUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRolUsuariosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnRolUsuariosActionPerformed

    private void btnUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUsuariosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnUsuariosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VistaDashBoardAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VistaDashBoardAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VistaDashBoardAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VistaDashBoardAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VistaDashBoardAdmin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnRolUsuarios;
    public javax.swing.JButton btnUsuarios;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JSeparator jSeparator2;
    public javax.swing.JPanel panelContenedor;
    private javax.swing.JPanel panelEnca;
    private javax.swing.JPanel panelMenu;
    // End of variables declaration//GEN-END:variables
}
